import React,{useState} from 'react';
type Tab='overview'|'map'|'objects'|'alerts'|'more';
const objects=[
 {name:'Гидропост Петропавловск',type:'Гидрологический пост',value:'742 см',status:'Внимание',cls:''},
 {name:'Защитная дамба Ущева',type:'Защитное гидротехническое сооружение',value:'DEMO-риск: высокий',status:'Высокий риск',cls:'high'},
 {name:'НС-1 (Насосная станция)',type:'Насосная станция',value:'Готовность: контроль',status:'Внимание',cls:''},
 {name:'Река Есиль',type:'Водный объект',value:'Скорость: 1,45 м/с',status:'Внимание',cls:''},
 {name:'Сергеевский гидроузел',type:'Гидроузел',value:'Сброс: 185 м³/с',status:'Норма',cls:'normal'},
 {name:'Петропавловский гидроузел',type:'Гидроузел',value:'Штатный режим',status:'Норма',cls:'normal'}];
const alerts=[
 ['Высокий риск','Защитная дамба Ущева','Тестовый сценарий: требуется проверка доказательной базы и контроль параметров.'],
 ['Внимание','Гидропост Петропавловск','DEMO-тренд +8 см/сут. До предупредительной отметки 8 см.'],
 ['Внимание','НС-1','Проверить готовность резервных насосов и источников электропитания.']];
function Header(){return <div className="head"><div className="brand">ПРОГНОСТИКА <span className="demo">DEMO</span></div><div className="sub">Мониторинг и прогнозирование гидрологических рисков · Петропавловск</div></div>}
function Overview(){return <div className="page"><div className="card risk"><div className="muted">ТЕКУЩАЯ ОБСТАНОВКА</div><div className="title amber" style={{fontSize:20,marginTop:5}}>Внимание</div><div className="muted">Повышенный контроль отдельных объектов · обновлено 09:00</div></div><div className="grid"><div className="metric"><span className="muted">Уровень воды</span><b>742 см</b><small className="amber">+8 см/сут</small></div><div className="metric"><span className="muted">Прогноз +24 ч</span><b>750 см</b><small className="amber">предупр. порог</small></div><div className="metric"><span className="muted">Повышенный риск</span><b>5</b><small>из 8 объектов</small></div><div className="metric"><span className="muted">Активные события</span><b>3</b><small>DEMO</small></div></div><div className="section">Прогноз уровня на 5 суток <span className="demo">DEMO</span></div><div className="card"><div className="chart">{[742,750,758,754,746].map((v,i)=><div className="bar" key={i} style={{height:(45+(v-740)*3)+'px'}}><span>{v}</span></div>)}</div><div className="muted" style={{textAlign:'center',marginTop:8}}>Сегодня · +1 · +2 · +3 · +4 суток</div></div><div className="section">Требуют внимания</div>{objects.filter(o=>o.status!=='Норма').map((o,i)=><ObjectCard key={i} o={o}/>)}</div>}
function ObjectCard({o}:{o:any}){return <div className={'card '+(o.cls||'risk')}><div className="obj"><div><div className="title">{o.name}</div><div className="muted">{o.type}</div><div style={{fontSize:12,marginTop:8}}>{o.value}</div></div><span className={'pill '+o.cls}>{o.status}</span></div></div>}
function Map(){return <div className="page"><div className="section">Пилотный контур</div><div className="map"><div className="river"></div><div className="pin" style={{left:'48%',top:'43%'}}></div><div className="pin" style={{left:'64%',top:'25%',background:'#f43f5e'}}></div><div className="pin" style={{left:'30%',top:'64%',background:'#22c55e'}}></div></div><div className="notice" style={{marginTop:10}}>Демонстрационная схема. Не является источником географических координат. Полноценная ГИС подключается на следующем этапе.</div></div>}
function Objects(){return <div className="page"><div className="section">Контролируемые объекты ({objects.length})</div>{objects.map((o,i)=><ObjectCard key={i} o={o}/>)}</div>}
function Alerts(){return <div className="page"><div className="section">События и предупреждения</div>{alerts.map((a,i)=><div className={'card '+(i===0?'high':'risk')} key={i}><div className="obj"><div className="title">{a[1]}</div><span className={'pill '+(i===0?'high':'')}>{a[0]}</span></div><p className="muted" style={{fontSize:12,lineHeight:1.5}}>{a[2]}</p><div className="muted">Основание: встроенные DEMO-данные</div></div>)}</div>}
function More(){return <div className="page"><div className="section">О системе</div><div className="card"><div className="title">Прогностика Mobile MVP 0.1</div><p className="muted" style={{lineHeight:1.55}}>Мобильный интерфейс информационно-аналитической системы мониторинга водных объектов, гидротехнических сооружений и прогнозирования гидрологических рисков.</p></div><div className="section">Архитектурный принцип</div><div className="notice">Источник числа ≠ ИИ. Источник инженерной формулы ≠ ИИ. ИИ может находить, связывать и объяснять данные, но не подменяет измерения и утверждённые расчётные методики.</div><div className="section">Доказательная цепочка</div><div className="card"><div className="row"><span>Источник</span><b>DEMO</b></div><div className="row"><span>Данные</span><b>Встроенный набор</b></div><div className="row"><span>Расчёт</span><b>DEMO-модель</b></div><div className="row"><span>Результат</span><b>Риск</b></div><div className="row"><span>Действие</span><b>Рекомендация</b></div></div><div className="section">Планируемые подключения</div><div className="card muted">Казгидромет · SCADA · Sentinel-1/InSAR · Sentinel-2 · БПЛА · пьезометры · GNSS · DAS · Risk Engine</div></div>}
export default function App(){const [tab,setTab]=useState<Tab>('overview');return <div className="app"><Header/>{tab==='overview'?<Overview/>:tab==='map'?<Map/>:tab==='objects'?<Objects/>:tab==='alerts'?<Alerts/>:<More/>}<div className="nav">{([['overview','▦','Обстановка'],['map','⌖','Карта'],['objects','◆','Объекты'],['alerts','◉','События'],['more','≡','Ещё']] as [Tab,string,string][]).map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i>{icon}</i>{label}</button>)}</div><div className="notice" style={{margin:'10px 12px'}}>Демонстрационная версия. Все числовые значения являются тестовыми и не являются фактическими гидрологическими наблюдениями или инженерными заключениями.</div></div>}
